changkun/modern-cpp-tutorial

- README.md
- book/4-containers.md
> 修正 unordered_map 笔误

- book/02-usability.md
typename 和 class 还是有一点区别的，在STL中尤其明显。只是不知道我这样修改后，是否影响本书后面的内容...   : D
> fix the difference between typename and class

- book/zh-cn/03-runtime.md
有几处看着挺奇怪，估计是笔误。所以我凭自己的想象修改了一下。
> Fix typo in 03-runtime.md.

- book/zh-cn/02-usability.md
> adjust indent

- book/en-us/02-usability.md
- code/2/2.01.nullptr.cpp
Fixed typo "doen't -> doesn't".
- Fix typo in Chapter 2.1
> fixed typo in code

- book/zh-cn/02-usability.md
fix indent: 
```cpp
template <typename T, typename U>
auto add(T t, U u) {
return t+u;
}
``` 
=>
```cpp
template <typename T, typename U>
auto add(T t, U u) {
return t+u;
}
```
> book: fix a minor typo

- book/en-us/02-usability.md
Small enhancement for wording in section mentioning decltype.
> Improve wording for decltype sentence

- book/en-us/07-thread.md
- book/zh-cn/04-containers.md
- book/zh-cn/07-thread.md
修复一些代码错误
- 解决格式问题
在book / zh-cn / 04-containers.md中存在格式问题影响阅读
- 解决代码错误
在book/zh-cn/07-thread.md中的一块代码缺少main函数
> fix code errors

- README-zh-cn.md
Please describe the motivation of this pull request, and what problem was solved in this PR.
- Fix typo error of XXX
- Add description regarding XXX feature
- Resolve error content of XXX
---
此处详细说明 PR 的动机是什么、解决了什么样的问题。
- 修复了 XXX 的 typo 错误
- 增加了 XXX 相关的说明
- 解决了关于 XXX 的描述性错误
如果有请注明
> fix pdf link

- book/en-us/01-intro.md
Fix typo in a link to further reading list.
- Fix typo in a link
> Update link to further readings

- book/en-us/00-preface.md
- book/en-us/01-intro.md
- book/en-us/02-usability.md
- book/en-us/03-runtime.md
- book/en-us/04-containers.md
- book/en-us/05-pointers.md
- book/en-us/06-regex.md
- book/en-us/07-thread.md
- book/en-us/09-others.md
- book/en-us/10-cpp20.md
resolve #184 =
Fixed all the issues I found in the book folder and changed them.
- Fix typo error of chapter 00, 01, 02, 03, 04, 05, 06, 07, 09, 10
---
> typo and grammar fixes

- book/zh-cn/03-runtime.md
Please describe the motivation of this pull request, and what problem was solved in this PR.
- Fix typo error of XXX
- Add description regarding XXX feature
- Resolve error content of XXX
---
多打了一个“而”字，导致的病句
- 删除一个“而”字
如果有请注明
> book: typo fix

- book/en-us/03-runtime.md
- book/zh-cn/03-runtime.md
解决issue #203
此处详细说明 PR 的动机是什么、解决了什么样的问题。
- 修复chapter03中字符串拼接结果的typo错误
-
> book: typo fix #203

- book/en-us/02-usability.md
- book/zh-cn/02-usability.md
Add missing semicolons for the example code snippet.
- add semicolons.
---
示例代码中缺少分号。
- 修复了示例代码中缺少的分号。
如果有请注明
> book: add missing semicolon

- book/en-us/07-thread.md
- Three typos in chapter 7 are spotted.
- Fix the three typos.
> book: fix typo

- .gitignore
Hi, thanks a lot for the excellent book! Start reading it with great enjoy, but found out when building on local to make some pulls, those asset files have not been ignored yet and a bit annoying.
This pull ignores some assets while building the book site on local.
- Fix typo error of XXX
- Add description regarding XXX feature
- Resolve error content of XXX
---
此处详细说明 PR 的动机是什么、解决了什么样的问题。
- 修复了 XXX 的 typo 错误
- 增加了 XXX 相关的说明
- 解决了关于 XXX 的描述性错误
如果有请注明
> Ignore some assets on build site on local

- book/en-us/07-thread.md
- book/en-us/08-filesystem.md
Hi!
First, thanks a lot for excellent book! I have read it with great enjoy.
Here are a few typos fixing.
> book: Fixed a few typos

- book/en-us/02-usability.md
**Resolve issue:** The code was not displaying correctly in the pdf file.
The code in this part was not displaying correctly in the pdf file, so i've added a line wrap.
- Added a line break because the code was not displaying correctly in the pdf file.
How the text was displayed:
> Added a line break because the code was not displaying correctly in the pdf file.

- book/en-us/01-intro.md
Please describe the motivation of this pull request, and what problem was solved in this PR.
- Fix typo error of XXX
- Add description regarding XXX feature
- Resolve error content of XXX
---
此处详细说明 PR 的动机是什么、解决了什么样的问题。
- 修复了 XXX 的 typo 错误
- 增加了 XXX 相关的说明
- 解决了关于 XXX 的描述性错误
如果有请注明
> Fix incorrect translation

- book/en-us/02-usability.md
Fix some typo error or not sync the newest version.
- Fix typo error of chapter 02
> fix: typo error

- book/en-us/07-thread.md
- book/zh-cn/07-thread.md
> “堆栈回退”改为“栈回溯”
