changkun/modern-cpp-tutorial

- book/03-runtime.md
感谢作者辛勤劳动，我也正在学习这本书，有些代码的缩进有问题，可以会影响阅读体验
> fix the code indent

- book/zh-cn/07-thread.md
- code/7/7.2.cpp
在 producer 将 `done` 赋值为 `true` 之前，如果 consumer 已经处理完最后一个数据并再次进入了等待，那么即使被唤醒，也无法跳出检查条件变量 `notified` 的循环。
> fix potential endless loop

- code/2/2.05.structured.binding.cpp
The header  <tuple> is missing. After adding it, it compiles fine with clang in c++17 mode.
> Fix compilation error for structured binding

- book/zh-cn/05-pointers.md
> 智能指针访问，应该使用 ->

- CONTRIBUTING.md
- README.md
Resolve #92
After finding this project, I thought it was an amazing initiative and I'd love to help out!
Starting at the basics (CONTRIBUTING & README), I found some sentences that could be improved a little so I decided to help.
- General edits of the README.md file
- General edits of the CONTRIBUTING.md file
> Rework of English part of README and CONTRIBUTING

- book/en-us/02-usability.md
- book/zh-cn/02-usability.md
decltype应当与typeof更相似,而非sizeof
- 解决了关于 decltype 的描述性错误 (包括中文与英文版本)
无
> Fix the wrong about delctype

- book/en-us/02-usability.md
- 文件路径：book/en-us/02-usability.md
- 原文段落：
```
The purpose of `nullptr` appears to replace `NULL`. In a sense, 
traditional C++ treats `NULL` and `0` as the same thing, 
depending on how the compiler defines NULL, 
and some compilers define NULL as `((void*)0)` Some will define it directly as `0`.
C++ ** does not allow ** to implicitly convert `void *` to other types. 
But if the compiler tries to define `NULL` as `((void*)0)`, then in the following code:
```
```
The purpose of `nullptr` appears to replace `NULL`. In a sense, 
traditional C++ treats `NULL` and `0` as the same thing, 
depending on how the compiler defines NULL, 
and some compilers define NULL as `((void*)0)` Some will define it directly as `0`.
C++ **does not allow** to implicitly convert `void *` to other types. 
But if …
```
> book/en: fix typos

- book/en-us/01-intro.md
Fix a typo.
- Fix typo error of 01-intro.md line 96.
> comple -> compile
> fix a typo on intro.md line 96

- book/zh-cn/01-intro.md
resolve #149 
A line break was missing in the Chinese version of chapter 1 section 1. This has caused the "inconsistent PDF rendering" between the English and Chinese version.
- Added an empty line in book/zh-cn/01-intro.md
---
修复了PDF中文版显示效果和英文版不一致的问题 (#149)。
- 在 book/zh-cn/01-intro.md 里添加了一个空行
（完整PDF：[modern-cpp-tutorial-zh-cn.pdf](https://github.com/changkun/modern-cpp-tutorial/files/5861473/modern-cpp-tutorial-zh-cn.pdf)）
> Added a line break in chapter 1

- book/en-us/04-containers.md
- book/zh-cn/04-containers.md
resolve #176 
调整了 `tuple_index` 函数中传参的顺序，原文弄反了。
- 修复了 book/zh-cn/02-containers.md, book/en-us/02-containers.md 中最后一段代码的 typo
> 修复了中英文第四章第 3 节最后一段代码中 `tuple_index` 的参数顺序 typo

- book/en-us/02-usability.md
- book/zh-cn/02-usability.md
The example of this section is incorrect. It is totally OK to just write `add(1, 3)` without default parameters even in C++98, since the compiler will deduce the type.
What's more, this feature is even not a C++11 feature. So I just delete it.
As the title shows
https://en.cppreference.com/w/cpp/language/template_parameters
https://en.cppreference.com/w/cpp/language/template_argument_deduction
> Remove ch2 - default template parameters

- book/zh-cn/09-others.md
Section 9.2 noexcept: my_throw() -> may_throw()
- Fix a typo in section 9.2
- my_throw() -> may_throw()
none
---
第9.2节noexcept：my_throw() -> may_throw()
- 改正一个9.2节的拼写错误
- my_throw() -> may_throw()
无
第192行代码的的变动是无意造成的，并未修改任何内容
> Fix a typo in section 9.2

- book/en-us/04-containers.md
- book/zh-cn/04-containers.md
Re-compose words to avoid words out of compiled pdf's margin. 
Before:
After:
---
重新组织句子结构使编译后的 PDF 排版字符不超出边缘。
之前：
之后：
> book: re-compose words to avoid out of pdf's margin

- book/en-us/03-runtime.md
There is no notion of linearity in this book. However, the context makes it clear that non-constant values are meant. So let us fix that.
- Use adjective non-constant; not non-linear
> book: “non-linear” should be “non-constant”

- book/en-us/03-runtime.md
- Fix a broken bold markdown in 03-runtime.md
> Fix bold in 03-runtime.md

- book/en-us/03-runtime.md
• s1 is not defined/declared anywhere
• lv1 is actually used
The variable s1 is undefined in this example. I am sure lv1 is meant.
- Fix variable name
> book: fix variable name: s1 → lv1

- book/en-us/03-runtime.md
- book/zh-cn/03-runtime.md
The previous statement about string literal is incorrect. [According to cppreference](https://en.cppreference.com/w/cpp/language/value_category#lvalue), a string literal is an lvalue forever, [which is an array of `const char`](https://en.cppreference.com/w/cpp/language/string_literal).
- Fix the statement about string literal in 03-runtime.md
+ https://en.cppreference.com/w/cpp/language/value_category#lvalue
+ https://en.cppreference.com/w/cpp/language/string_literal
+ https://eel.is/c++draft/expr.prim#literal
---
原来对于“字符串字面量在类中是右值”的叙述有误。根据 [cppreference 对于左值的表述](https://zh.cppreference.com/w/cpp/language/value_category#.E5.B7.A6.E5.80.BC)，字符串字面量永远是一个左值，[其类型是 `const char` 数组](https://zh.cppreference.com/w/cpp/language/string_literal)。
- 修复了 03-runtime.md 中关于字符串字面量的表述
+ …
> fix: correct errors in string literal explanation

- book/en-us/02-usability.md
- book/zh-cn/02-usability.md
Fix typo error
- Fix typo error of 2.3 type inference: itr -> it
修正typo错误
- 修复了2.3 类型推导的 typo 错误：itr -> it
> fix: typo error of 2.3

- book/en-us/02-usability.md
This PR removes a typo in chapter 2; removes unnecessary words.
- Fix a typo in chapter 2
N/A
> Fix a typo: remove unnecessary words

- book/en-us/02-usability.md
- book/zh-cn/02-usability.md
resolve #266
We didn't explicitly say `auto` can't used for function parameter type deduction. Also, such deduction is available in generic lambdas since C++14.
- Resolve error content of function parameter type deduction
- [WG21 N3649](https://wg21.link/n3649)
- [WG21 P1141R2](https://wg21.link/p1141r2)
---
我们没有明确说过 `auto` 不能用于函数参数类型推导。另外， C++14 起这种推导已经可用于 lambda 表达式。
- 解决了关于函数参数推导的描述性错误
- [WG21 N3649](https://wg21.link/n3649)
- [WG21 P1141R2](https://wg21.link/p1141r2)
> book: correct description of function template parameter deduction from `auto`

- book/zh-cn/02-usability.md
02 usability章节里的强类型枚举中，代码示例的注释只写了 会输出，但是没有写结果。 英文版中是有true的。 
- 增加了强类型枚举中代码示例的输出结果
> Add missing result.
